In [1]:
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline        

import numpy as np
import pandas as pd 

from sklearn.datasets import make_circles, load_boston
from sklearn.model_selection import train_test_split as tts

from sklearn.linear_model import LinearRegression as LinReg
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
corpus = ['Hola como estan el dia de hoy como',
         'Ojala no llueva el dia de hoy',
         'tengo hambre',
         'tenemos frio',
         'si llueve hace frio']

In [3]:
vecto = CountVectorizer()

x = vecto.fit_transform(corpus)
print(vecto.get_feature_names())

['como', 'de', 'dia', 'el', 'estan', 'frio', 'hace', 'hambre', 'hola', 'hoy', 'llueva', 'llueve', 'no', 'ojala', 'si', 'tenemos', 'tengo']

In [4]:
x.toarray()

array([[2, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]], dtype=int64)

In [5]:
len(vecto.get_feature_names())

17

In [6]:
len(x.toarray()[0])

17

In [7]:
from sklearn import preprocessing

In [8]:
en = preprocessing.LabelEncoder()
en

LabelEncoder()

In [9]:
en.fit(['alto','bajo','alto','medio','muy alto','bajo','muy alto'])

LabelEncoder()

In [10]:
en.classes_

array(['alto', 'bajo', 'medio', 'muy alto'], dtype='<U8')

In [11]:
en.transform(['medio','muy alto','alto','bajo','alto','bajo'])

array([2, 3, 0, 1, 0, 1], dtype=int64)

In [12]:
pd.get_dummies(['alto','bajo','alto','medio','muy alto','bajo','muy alto'])

   alto  bajo  medio  muy alto
0     1     0      0         0
1     0     1      0         0
2     1     0      0         0
3     0     0      1         0
4     0     0      0         1
5     0     1      0         0
6     0     0      0         1

In [13]:
en.inverse_transform([3,3,1,0,2])

array(['muy alto', 'muy alto', 'bajo', 'alto', 'medio'], dtype='<U8')

In [14]:
#en.inverse_transform([3,3,1,0,2,4])

In [15]:
titanic = pd.read_csv('data/titanic.csv')

In [16]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler

In [19]:
trans = ColumnTransformer(
[('one_hot',OneHotEncoder(),[4]),
('norm', StandardScaler(), [9])])

In [20]:
pd.DataFrame(trans.fit_transform(titanic))

       0    1         2
0    0.0  1.0 -0.502445
1    1.0  0.0  0.786845
2    1.0  0.0 -0.488854
3    1.0  0.0  0.420730
4    0.0  1.0 -0.486337
..   ...  ...       ...
886  0.0  1.0 -0.386671
887  1.0  0.0 -0.044381
888  1.0  0.0 -0.176263
889  0.0  1.0 -0.044381
890  0.0  1.0 -0.492378

[891 rows x 3 columns]

In [21]:
import zipfile

In [22]:
zf = zipfile.ZipFile('data/mahindra.zip')

In [23]:
zf

In [24]:
ctr = pd.read_csv(zf.open('test.csv'))
ctr.head()

,reservation_id,booking_date,checkin_date,checkout_date,channel_code,main_product_code,numberofadults,numberofchildren,persontravellingid,resort_region_code,...,season_holidayed_code,state_code_residence,state_code_resort,total_pax,member_age_buckets,booking_type_code,memberid,cluster_code,reservationstatusid_code,resort_id
0,7dae1ce6bc8f69481328f2be5c4943077dad5598b5f66d...,05/04/18,05/04/18,06/04/18,3,2,2,0,45,3,...,2.0,2.0,3,3,H,1,2114944930dcc42ce5b9b50ae965cf8a9c04e46be63d84...,A,C,9f14025af0065b30e47e23ebb3b491d39ae8ed17d33739...
1,fe0d4e444e1818436c88f72f1cf800536c2f785e59baeb...,24/05/15,23/06/15,27/06/15,1,2,4,0,45,1,...,2.0,2.0,4,2,H,1,2114944930dcc42ce5b9b50ae965cf8a9c04e46be63d84...,F,A,e7f6c011776e8db7cd330b54174fd76f7d0216b612387a...
2,540bd4285ad8168e8388f84ee74a82cd4f97dc0a404d3e...,21/07/15,07/08/15,10/08/15,3,2,3,0,45,2,...,4.0,2.0,2,3,H,1,2114944930dcc42ce5b9b50ae965cf8a9c04e46be63d84...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...
3,09593c907ae262e46f655b4db9e14f54a19eadcfdd2679...,31/07/15,22/10/15,25/10/15,1,2,3,0,45,1,...,2.0,2.0,6,3,H,1,2114944930dcc42ce5b9b50ae965cf8a9c04e46be63d84...,F,A,49d180ecf56132819571bf39d9b7b342522a2ac6d23c14...
4,f4c50caac68051faf37551d70bb17eebef2a20e2244cb1...,01/07/16,01/10/16,05/10/16,1,2,4,0,45,1,...,2.0,2.0,11,2,H,1,2114944930dcc42ce5b9b50ae965cf8a9c04e46be63d84...,F,A,e29c9c180c6279b0b02abd6a1801c7c04082cf486ec027...

In [25]:
ctr_id = [x for x in ctr.columns if x.endswith('id')]
ctr_id

['reservation_id', 'persontravellingid', 'memberid', 'resort_id']

In [26]:
for i in ctr_id:
    ctr.drop(i, inplace = True, axis = 1)

In [27]:
ctr

,booking_date,checkin_date,checkout_date,channel_code,main_product_code,numberofadults,numberofchildren,resort_region_code,resort_type_code,room_type_booked_code,roomnights,season_holidayed_code,state_code_residence,state_code_resort,total_pax,member_age_buckets,booking_type_code,cluster_code,reservationstatusid_code
0,05/04/18,05/04/18,06/04/18,3,2,2,0,3,3,4,1,2.0,2.0,3,3,H,1,A,C
1,24/05/15,23/06/15,27/06/15,1,2,4,0,1,1,4,8,2.0,2.0,4,2,H,1,F,A
2,21/07/15,07/08/15,10/08/15,3,2,3,0,2,2,2,3,4.0,2.0,2,3,H,1,D,A
3,31/07/15,22/10/15,25/10/15,1,2,3,0,1,1,2,3,2.0,2.0,6,3,H,1,F,A
4,01/07/16,01/10/16,05/10/16,1,2,4,0,1,2,3,8,2.0,2.0,11,2,H,1,F,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146760,20/02/19,21/02/19,22/02/19,1,3,2,0,1,1,3,1,4.0,10.0,1,2,E,1,E,A
146761,21/02/19,21/02/19,22/02/19,3,4,3,0,2,2,2,1,3.0,13.0,2,4,B,1,D,A
146762,23/02/19,24/02/19,26/02/19,1,1,5,0,1,1,2,4,4.0,3.0,6,3,F,1,F,A
146763,26/02/19,01/03/19,02/03/19,1,7,2,2,3,3,3,2,3.0,5.0,3,4,I,1,A,A
146764,27/02/19,01/03/19,02/03/19,2,4,2,0,2,1,4,1,3.0,8.0,7,2,B,2,C,A

In [28]:
for e in ctr.select_dtypes('float64').columns:
    ctr[e] = ctr[e].astype('float16')

In [29]:
ctr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146765 entries, 0 to 146764
Data columns (total 19 columns):
booking_date                146765 non-null object
checkin_date                146765 non-null object
checkout_date               146765 non-null object
channel_code                146765 non-null int64
main_product_code           146765 non-null int64
numberofadults              146765 non-null int64
numberofchildren            146765 non-null int64
resort_region_code          146765 non-null int64
resort_type_code            146765 non-null int64
room_type_booked_code       146765 non-null int64
roomnights                  146765 non-null int64
season_holidayed_code       146730 non-null float16
state_code_residence        144505 non-null float16
state_code_resort           146765 non-null int64
total_pax                   146765 non-null int64
member_age_buckets          146765 non-null object
booking_type_code           146765 non-null int64
cluster_code                146765 non-null object
reservationstatusid_code    146765 non-null object
dtypes: float16(2), int64(11), object(6)
memory usage: 19.6+ MB

In [30]:
for e in ctr.select_dtypes('integer').columns:
    ctr[e] = pd.to_numeric(ctr[e], downcast='integer')
    
ctr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146765 entries, 0 to 146764
Data columns (total 19 columns):
booking_date                146765 non-null object
checkin_date                146765 non-null object
checkout_date               146765 non-null object
channel_code                146765 non-null int8
main_product_code           146765 non-null int8
numberofadults              146765 non-null int8
numberofchildren            146765 non-null int8
resort_region_code          146765 non-null int8
resort_type_code            146765 non-null int8
room_type_booked_code       146765 non-null int8
roomnights                  146765 non-null int8
season_holidayed_code       146730 non-null float16
state_code_residence        144505 non-null float16
state_code_resort           146765 non-null int8
total_pax                   146765 non-null int8
member_age_buckets          146765 non-null object
booking_type_code           146765 non-null int8
cluster_code                146765 non-null object
reservationstatusid_code    146765 non-null object
dtypes: float16(2), int8(11), object(6)
memory usage: 8.8+ MB

# Regresion-se busca un numero

### Regresión lineal

Se han de tener algunas suposiciones previas:

+ Exogeneidad débil (predictores libres de error)
+ Linealidad
+ Homocedasticidad (Var=cte) y Esperanza nula (**E**=0), la esperanza es la media
+ Independencia de los errores
+ Falta de colinealidad (independencia lineal)

$$y=\beta_0+\beta_1x_1+\beta_2x_2+\beta_3x_3+\ldots+\beta_nx_n+\epsilon$$

El objetivo de la regresion lineal es obtener los $\beta$:
+ Algebraicamente:

$$\vec{\beta} = (X^{T}X)^{-1}X^{T}y$$

+ Minimos cuadrados

$$MSE = \frac{1}{n} \sum_{i=1}^{n} (y-\hat{y})^{2}$$

Ejemplo)

$y = \beta_0 + \beta_1x_1 + \epsilon$

Entonces, derivando MSE e igualando a 0:

$\beta_0 = \frac{\sum y - \beta_1\sum x}{n} = \bar{y} - \beta_1\bar{x}$

$\beta_1=\frac{\sum (x-\hat{x})(y-\hat{y})}{\sum (x-\hat{x})}$

In [31]:
boston = load_boston()

In [32]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [33]:
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**

    :Number of Instances: 506

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
        - LSTAT    % lower status of the population
        - MEDV     Median value of owner-occupied homes in $1000's

    :Missing Attribute Values: None

    :Creator: Harrison, D. and Rubinfeld, D.L.

This is a copy of UCI ML housing dataset.
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/


This dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.

The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
prices and the demand for clean air', J. Environ. Economics & Management,
vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
...', Wiley, 1980.   N.B. Various transformations are used in the table on
pages 244-261 of the latter.

The Boston house-price data has been used in many machine learning papers that address regression
problems.

.. topic:: References

   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.
   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.

In [34]:
df=pd.DataFrame(boston.data, columns=boston.feature_names)
df['price'] = boston.target
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [35]:
X = boston.data
y = boston.target

In [36]:
X.shape

(506, 13)

In [37]:
X_train, X_test, y_train, y_test = tts(X,y ,test_size = .2)

In [38]:
print(X_train.shape,y_train.shape)

(404, 13) (404,)

In [39]:
linreg = LinReg()
linreg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
y_pred = linreg.predict(X_test)

In [41]:
from sklearn.metrics import r2_score

In [42]:
r2_score(y_pred,y_test)

0.571999087844611

In [43]:
linreg.coef_

array([-1.01185861e-01,  4.46745071e-02,  3.27320182e-02,  2.93777096e+00,
       -1.71810566e+01,  3.72758618e+00,  5.03795586e-03, -1.41523134e+00,
        2.92812442e-01, -1.16966583e-02, -1.00868876e+00,  8.76013179e-03,
       -5.41227538e-01])

In [44]:
len(linreg.coef_)

13

##### Regularización

**Función de Coste o de Pérdida (J)** = Función a minimizar

En el caso de la regresión lineal: 
$$J=MSE$$


La regularización es una medida/penalización de la complejidad del modelo. Se añade un término a J que depende del tipo de regularización:

$$J = MSE + \alpha · T$$


+ Lasso (L1, norma 1):

$$T=\frac{1}{n}\sum_{i}  |\beta_i|$$

Muy útil si se sospecha que hay características irrelevantes. Se favorece $\beta \approx 0$

+ Ridge (L2):

$$T=\frac{1}{2n}\sum_{i}  \beta_{i}^{2}$$

Muy útil si se sospecha que existe correlación entre las características, minimiza esa correlación. Funciona mejor si todas son relevantes.

+ ElasticNet (L1+L2):

$$T=r·L1 + (1-r)·L2$$

Se usa cuando hay muchas características.

In [45]:
from sklearn.linear_model import Ridge

In [46]:
model_r = Ridge(alpha = 0.001, fit_intercept=True, normalize=True)

In [47]:
model_r.fit(X_train, y_train)

Ridge(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=True, random_state=None, solver='auto', tol=0.001)

In [48]:
y_pred = model_r.predict(X_test)

In [49]:
r2_score(y_pred,y_test)

0.571407567169991

In [50]:
model_r.coef_

array([-1.00702184e-01,  4.43725219e-02,  3.11297234e-02,  2.94636615e+00,
       -1.70581127e+01,  3.73519693e+00,  4.90965367e-03, -1.40889643e+00,
        2.88714381e-01, -1.15061728e-02, -1.00636017e+00,  8.75646201e-03,
       -5.40237651e-01])

In [51]:
new = X[0].reshape(1,-1)

In [52]:
new

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [53]:
model_r.predict(new)

array([30.15896226])

# Maquina de soporte Vectorial

![](data\2circles.jpg)

![](data/2circ_var.jpg)

![](data/2circ_pol.jpg)

###### SVM

![](data/svm.png)

Genera un hiperplano (n-1)dimensional para separar los datos. Este primer plano es el llamado clasificador lineal (maximizando la distancia a los puntos).

$$\vec{\omega}\vec{x}-b=0$$

donde :

$\omega$ es el vector normal al plano
$x$ son los datos
$b$ es el sesgo

In [54]:
import warnings
warnings.simplefilter('ignore')

In [55]:
from sklearn.svm import SVR

In [56]:
svr = SVR(kernel = 'linear', epsilon= 1.5)
svr.fit(X_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=1.5, gamma='scale',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [57]:
y_pred = svr.predict(X_test)

In [58]:
r2_score(y_pred,y_test)

0.5539751431977112

In [59]:
svr.coef_

array([[-0.10938558,  0.02596508, -0.02047703,  1.01051828, -1.75665619,
         5.05128836, -0.03171131, -0.87855021,  0.15346528, -0.00994279,
        -0.69346962,  0.01117441, -0.37035457]])

In [60]:
svr.predict(new)

array([29.06266086])

In [61]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [62]:
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
from sklearn import tree

In [63]:
X = df['TAX']
Y = df['price']

In [64]:
rg = DecisionTreeRegressor(max_depth = 5, criterion = 'mse')

In [65]:
X.values

array([296., 242., 242., 222., 222., 222., 311., 311., 311., 311., 311.,
       311., 311., 307., 307., 307., 307., 307., 307., 307., 307., 307.,
       307., 307., 307., 307., 307., 307., 307., 307., 307., 307., 307.,
       307., 307., 279., 279., 279., 279., 252., 252., 233., 233., 233.,
       233., 233., 233., 233., 233., 233., 243., 243., 243., 243., 469.,
       226., 313., 256., 284., 284., 284., 284., 284., 284., 216., 337.,
       337., 345., 345., 345., 305., 305., 305., 305., 398., 398., 398.,
       398., 398., 398., 281., 281., 281., 281., 247., 247., 247., 247.,
       270., 270., 270., 270., 270., 270., 270., 276., 276., 276., 276.,
       276., 384., 384., 384., 384., 384., 384., 384., 384., 384., 384.,
       384., 432., 432., 432., 432., 432., 432., 432., 432., 432., 188.,
       188., 188., 188., 188., 188., 188., 437., 437., 437., 437., 437.,
       437., 437., 437., 437., 437., 437., 437., 437., 437., 437., 403.,
       403., 403., 403., 403., 403., 403., 403., 403., 403., 403., 403.,
       403., 403., 403., 403., 403., 403., 403., 403., 403., 403., 403.,
       403., 403., 403., 403., 403., 403., 403., 296., 296., 296., 296.,
       296., 296., 296., 193., 193., 193., 193., 193., 193., 193., 193.,
       398., 398., 398., 398., 398., 398., 265., 265., 255., 329., 329.,
       329., 402., 402., 348., 348., 224., 224., 277., 277., 277., 277.,
       277., 277., 277., 277., 277., 277., 277., 276., 276., 276., 276.,
       307., 307., 307., 307., 307., 307., 307., 307., 307., 307., 307.,
       307., 307., 307., 307., 307., 307., 307., 300., 300., 300., 300.,
       300., 300., 330., 330., 330., 330., 330., 330., 330., 330., 330.,
       330., 315., 315., 244., 264., 264., 264., 264., 264., 264., 264.,
       264., 264., 264., 264., 264., 223., 223., 223., 223., 223., 254.,
       254., 254., 254., 254., 216., 216., 216., 216., 198., 285., 300.,
       241., 293., 293., 293., 245., 245., 245., 289., 289., 289., 289.,
       289., 358., 358., 358., 329., 329., 329., 222., 222., 222., 222.,
       304., 304., 304., 304., 304., 304., 304., 304., 304., 304., 304.,
       304., 287., 287., 287., 287., 287., 287., 287., 287., 430., 430.,
       430., 304., 304., 224., 224., 224., 224., 224., 224., 224., 224.,
       284., 422., 370., 370., 352., 352., 351., 280., 335., 335., 411.,
       411., 187., 334., 334., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 666., 666., 666., 666., 666., 666., 666.,
       666., 666., 666., 666., 711., 711., 711., 711., 711., 391., 391.,
       391., 391., 391., 391., 391., 391., 273., 273., 273., 273., 273.])

In [66]:
X.values.reshape(-1,1)

array([[296.],
       [242.],
       [242.],
       [222.],
       [222.],
       [222.],
       [311.],
       [311.],
       [311.],
       [311.],
       [311.],
       [311.],
       [311.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [279.],
       [279.],
       [279.],
       [279.],
       [252.],
       [252.],
       [233.],
       [233.],
       [233.],
       [233.],
       [233.],
       [233.],
       [233.],
       [233.],
       [233.],
       [243.],
       [243.],
       [243.],
       [243.],
       [469.],
       [226.],
       [313.],
       [256.],
       [284.],
       [284.],
       [284.],
       [284.],
       [284.],
       [284.],
       [216.],
       [337.],
       [337.],
       [345.],
       [345.],
       [345.],
       [305.],
       [305.],
       [305.],
       [305.],
       [398.],
       [398.],
       [398.],
       [398.],
       [398.],
       [398.],
       [281.],
       [281.],
       [281.],
       [281.],
       [247.],
       [247.],
       [247.],
       [247.],
       [270.],
       [270.],
       [270.],
       [270.],
       [270.],
       [270.],
       [270.],
       [276.],
       [276.],
       [276.],
       [276.],
       [276.],
       [384.],
       [384.],
       [384.],
       [384.],
       [384.],
       [384.],
       [384.],
       [384.],
       [384.],
       [384.],
       [384.],
       [432.],
       [432.],
       [432.],
       [432.],
       [432.],
       [432.],
       [432.],
       [432.],
       [432.],
       [188.],
       [188.],
       [188.],
       [188.],
       [188.],
       [188.],
       [188.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [437.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [403.],
       [296.],
       [296.],
       [296.],
       [296.],
       [296.],
       [296.],
       [296.],
       [193.],
       [193.],
       [193.],
       [193.],
       [193.],
       [193.],
       [193.],
       [193.],
       [398.],
       [398.],
       [398.],
       [398.],
       [398.],
       [398.],
       [265.],
       [265.],
       [255.],
       [329.],
       [329.],
       [329.],
       [402.],
       [402.],
       [348.],
       [348.],
       [224.],
       [224.],
       [277.],
       [277.],
       [277.],
       [277.],
       [277.],
       [277.],
       [277.],
       [277.],
       [277.],
       [277.],
       [277.],
       [276.],
       [276.],
       [276.],
       [276.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [307.],
       [300.],
       [300.],
       [300.],
       [300.],
       [300.],
       [300.],
       [330.],
       [330.],
       [330.],
       [330.],
       [330.],
       [330.],
       [330.],
       [330.],
       [330.],
       [330.],
       [315.],
       [315.],
       [244.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [264.],
       [223.],
       [223.],
       [223.],
       [223.],
       [223.],
       [254.],
       [254.],
       [254.],
       [254.],
       [254.],
       [216.],
       [216.],
       [216.],
       [216.],
       [198.],
       [285.],
       [300.],
       [241.],
       [293.],
       [293.],
       [293.],
       [245.],
       [245.],
       [245.],
       [289.],
       [289.],
       [289.],
       [289.],
       [289.],
       [358.],
       [358.],
       [358.],
       [329.],
       [329.],
       [329.],
       [222.],
       [222.],
       [222.],
       [222.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [304.],
       [287.],
       [287.],
       [287.],
       [287.],
       [287.],
       [287.],
       [287.],
       [287.],
       [430.],
       [430.],
       [430.],
       [304.],
       [304.],
       [224.],
       [224.],
       [224.],
       [224.],
       [224.],
       [224.],
       [224.],
       [224.],
       [284.],
       [422.],
       [370.],
       [370.],
       [352.],
       [352.],
       [351.],
       [280.],
       [335.],
       [335.],
       [411.],
       [411.],
       [187.],
       [334.],
       [334.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [666.],
       [711.],
       [711.],
       [711.],
       [711.],
       [711.],
       [391.],
       [391.],
       [391.],
       [391.],
       [391.],
       [391.],
       [391.],
       [391.],
       [273.],
       [273.],
       [273.],
       [273.],
       [273.]])

In [67]:
rg.fit(X.values.reshape(-1,1),Y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [68]:
rg.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': 5,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': 'deprecated',
 'random_state': None,
 'splitter': 'best'}

In [69]:
rg.score(X.values.reshape(-1,1),Y)

0.3688468444837171

### Random Forest

![](data/RF.jpg)

Arboles de decisión.

+ Pros:

Modelos sencillos, se pueden visualizar. No necesitan preprocesar mucho los datos. Computacionalmente eficientes.

+ Contras:

Muy sensibles a pequeñas variaciones de los datos de entrada. Muy sensible a datos no balanceados. Muy dado al overfitting (poco sesgo, mucha varianza), más cuanto más profundo sea.

In [70]:
from sklearn.ensemble import RandomForestRegressor as RFR

In [71]:
help(RFR)

Help on class RandomForestRegressor in module sklearn.ensemble._forest:

class RandomForestRegressor(ForestRegressor)
 |  RandomForestRegressor(n_estimators=100, criterion='mse', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, ccp_alpha=0.0, max_samples=None)
 |
 |  A random forest regressor.
 |
 |  A random forest is a meta estimator that fits a number of classifying
 |  decision trees on various sub-samples of the dataset and uses averaging
 |  to improve the predictive accuracy and control over-fitting.
 |  The sub-sample size is always the same as the original
 |  input sample size but the samples are drawn with replacement if
 |  `bootstrap=True` (default).
 |
 |  Read more in the :ref:`User Guide <forest>`.
 |
 |  Parameters
 |  ----------
 |  n_estimators : integer, optional (default=10)
 |      The number of trees in the forest.
 |
 |      .. versionchanged:: 0.22
 |         The default value of ``n_estimators`` changed from 10 to 100
 |         in 0.22.
 |
 |  criterion : string, optional (default="mse")
 |      The function to measure the quality of a split. Supported criteria
 |      are "mse" for the mean squared error, which is equal to variance
 |      reduction as feature selection criterion, and "mae" for the mean
 |      absolute error.
 |
 |      .. versionadded:: 0.18
 |         Mean Absolute Error (MAE) criterion.
 |
 |  max_depth : integer or None, optional (default=None)
 |      The maximum depth of the tree. If None, then nodes are expanded until
 |      all leaves are pure or until all leaves contain less than
 |      min_samples_split samples.
 |
 |  min_samples_split : int, float, optional (default=2)
 |      The minimum number of samples required to split an internal node:
 |
 |      - If int, then consider `min_samples_split` as the minimum number.
 |      - If float, then `min_samples_split` is a fraction and
 |        `ceil(min_samples_split * n_samples)` are the minimum
 |        number of samples for each split.
 |
 |      .. versionchanged:: 0.18
 |         Added float values for fractions.
 |
 |  min_samples_leaf : int, float, optional (default=1)
 |      The minimum number of samples required to be at a leaf node.
 |      A split point at any depth will only be considered if it leaves at
 |      least ``min_samples_leaf`` training samples in each of the left and
 |      right branches.  This may have the effect of smoothing the model,
 |      especially in regression.
 |
 |      - If int, then consider `min_samples_leaf` as the minimum number.
 |      - If float, then `min_samples_leaf` is a fraction and
 |        `ceil(min_samples_leaf * n_samples)` are the minimum
 |        number of samples for each node.
 |
 |      .. versionchanged:: 0.18
 |         Added float values for fractions.
 |
 |  min_weight_fraction_leaf : float, optional (default=0.)
 |      The minimum weighted fraction of the sum total of weights (of all
 |      the input samples) required to be at a leaf node. Samples have
 |      equal weight when sample_weight is not provided.
 |
 |  max_features : int, float, string or None, optional (default="auto")
 |      The number of features to consider when looking for the best split:
 |
 |      - If int, then consider `max_features` features at each split.
 |      - If float, then `max_features` is a fraction and
 |        `int(max_features * n_features)` features are considered at each
 |        split.
 |      - If "auto", then `max_features=n_features`.
 |      - If "sqrt", then `max_features=sqrt(n_features)`.
 |      - If "log2", then `max_features=log2(n_features)`.
 |      - If None, then `max_features=n_features`.
 |
 |      Note: the search for a split does not stop until at least one
 |      valid partition of the node samples is found, even if it requires to
 |      effectively inspect more than ``max_features`` features.
 |
 |  max_leaf_nodes : int or None, optional (default=None)
 |      Grow trees with ``max_leaf_nodes`` in best-first fashion.
 |      Best nodes are defined as relative reduction in impurity.
 |      If None then unlimited number of leaf nodes.
 |
 |  min_impurity_decrease : float, optional (default=0.)
 |      A node will be split if this split induces a decrease of the impurity
 |      greater than or equal to this value.
 |
 |      The weighted impurity decrease equation is the following::
 |
 |          N_t / N * (impurity - N_t_R / N_t * right_impurity
 |                              - N_t_L / N_t * left_impurity)
 |
 |      where ``N`` is the total number of samples, ``N_t`` is the number of
 |      samples at the current node, ``N_t_L`` is the number of samples in the
 |      left child, and ``N_t_R`` is the number of samples in the right child.
 |
 |      ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
 |      if ``sample_weight`` is passed.
 |
 |      .. versionadded:: 0.19
 |
 |  min_impurity_split : float, (default=1e-7)
 |      Threshold for early stopping in tree growth. A node will split
 |      if its impurity is above the threshold, otherwise it is a leaf.
 |
 |      .. deprecated:: 0.19
 |         ``min_impurity_split`` has been deprecated in favor of
 |         ``min_impurity_decrease`` in 0.19. The default value of
 |         ``min_impurity_split`` will change from 1e-7 to 0 in 0.23 and it
 |         will be removed in 0.25. Use ``min_impurity_decrease`` instead.
 |
 |  bootstrap : boolean, optional (default=True)
 |      Whether bootstrap samples are used when building trees. If False, the
 |      whole datset is used to build each tree.
 |
 |  oob_score : bool, optional (default=False)
 |      whether to use out-of-bag samples to estimate
 |      the R^2 on unseen data.
 |
 |  n_jobs : int or None, optional (default=None)
 |      The number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,
 |      :meth:`decision_path` and :meth:`apply` are all parallelized over the
 |      trees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`
 |      context. ``-1`` means using all processors. See :term:`Glossary
 |      <n_jobs>` for more details.
 |
 |  random_state : int, RandomState instance or None, optional (default=None)
 |      Controls both the randomness of the bootstrapping of the samples used
 |      when building trees (if ``bootstrap=True``) and the sampling of the
 |      features to consider when looking for the best split at each node
 |      (if ``max_features < n_features``).
 |      See :term:`Glossary <random_state>` for details.
 |
 |  verbose : int, optional (default=0)
 |      Controls the verbosity when fitting and predicting.
 |
 |  warm_start : bool, optional (default=False)
 |      When set to ``True``, reuse the solution of the previous call to fit
 |      and add more estimators to the ensemble, otherwise, just fit a whole
 |      new forest. See :term:`the Glossary <warm_start>`.
 |
 |  ccp_alpha : non-negative float, optional (default=0.0)
 |      Complexity parameter used for Minimal Cost-Complexity Pruning. The
 |      subtree with the largest cost complexity that is smaller than
 |      ``ccp_alpha`` will be chosen. By default, no pruning is performed. See
 |      :ref:`minimal_cost_complexity_pruning` for details.
 |
 |      .. versionadded:: 0.22
 |
 |  max_samples : int or float, default=None
 |      If bootstrap is True, the number of samples to draw from X
 |      to train each base estimator.
 |
 |      - If None (default), then draw `X.shape[0]` samples.
 |      - If int, then draw `max_samples` samples.
 |      - If float, then draw `max_samples * X.shape[0]` samples. Thus,
 |        `max_samples` should be in the interval `(0, 1)`.
 |
 |      .. versionadded:: 0.22
 |
 |  Attributes
 |  ----------
 |  base_estimator_ : DecisionTreeRegressor
 |      The child estimator template used to create the collection of fitted
 |      sub-estimators.
 |
 |  estimators_ : list of DecisionTreeRegressor
 |      The collection of fitted sub-estimators.
 |
 |  feature_importances_ : ndarray of shape (n_features,)
 |      The feature importances (the higher, the more important the feature).
 |
 |  n_features_ : int
 |      The number of features when ``fit`` is performed.
 |
 |  n_outputs_ : int
 |      The number of outputs when ``fit`` is performed.
 |
 |  oob_score_ : float
 |      Score of the training dataset obtained using an out-of-bag estimate.
 |      This attribute exists only when ``oob_score`` is True.
 |
 |  oob_prediction_ : ndarray of shape (n_samples,)
 |      Prediction computed with out-of-bag estimate on the training set.
 |      This attribute exists only when ``oob_score`` is True.
 |
 |  Examples
 |  --------
 |  >>> from sklearn.ensemble import RandomForestRegressor
 |  >>> from sklearn.datasets import make_regression
 |
 |  >>> X, y = make_regression(n_features=4, n_informative=2,
 |  ...                        random_state=0, shuffle=False)
 |  >>> regr = RandomForestRegressor(max_depth=2, random_state=0)
 |  >>> regr.fit(X, y)
 |  RandomForestRegressor(max_depth=2, random_state=0)
 |  >>> print(regr.feature_importances_)
 |  [0.18146984 0.81473937 0.00145312 0.00233767]
 |  >>> print(regr.predict([[0, 0, 0, 0]]))
 |  [-8.32987858]
 |
 |  Notes
 |  -----
 |  The default values for the parameters controlling the size of the trees
 |  (e.g. ``max_depth``, ``min_samples_leaf``, etc.) lead to fully grown and
 |  unpruned trees which can potentially be very large on some data sets. To
 |  reduce memory consumption, the complexity and size of the trees should be
 |  controlled by setting those parameter values.
 |
 |  The features are always randomly permuted at each split. Therefore,
 |  the best found split may vary, even with the same training data,
 |  ``max_features=n_features`` and ``bootstrap=False``, if the improvement
 |  of the criterion is identical for several splits enumerated during the
 |  search of the best split. To obtain a deterministic behaviour during
 |  fitting, ``random_state`` has to be fixed.
 |
 |  The default value ``max_features="auto"`` uses ``n_features``
 |  rather than ``n_features / 3``. The latter was originally suggested in
 |  [1], whereas the former was more recently justified empirically in [2].
 |
 |  References
 |  ----------
 |
 |  .. [1] L. Breiman, "Random Forests", Machine Learning, 45(1), 5-32, 2001.
 |
 |  .. [2] P. Geurts, D. Ernst., and L. Wehenkel, "Extremely randomized
 |         trees", Machine Learning, 63(1), 3-42, 2006.
 |
 |  See Also
 |  --------
 |  DecisionTreeRegressor, ExtraTreesRegressor
 |
 |  Method resolution order:
 |      RandomForestRegressor
 |      ForestRegressor
 |      sklearn.base.RegressorMixin
 |      BaseForest
 |      sklearn.base.MultiOutputMixin
 |      sklearn.ensemble._base.BaseEnsemble
 |      sklearn.base.MetaEstimatorMixin
 |      sklearn.base.BaseEstimator
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, n_estimators=100, criterion='mse', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, ccp_alpha=0.0, max_samples=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from ForestRegressor:
 |
 |  predict(self, X)
 |      Predict regression target for X.
 |
 |      The predicted regression target of an input sample is computed as the
 |      mean predicted regression targets of the trees in the forest.
 |
 |      Parameters
 |      ----------
 |      X : array-like or sparse matrix of shape (n_samples, n_features)
 |          The input samples. Internally, its dtype will be converted to
 |          ``dtype=np.float32``. If a sparse matrix is provided, it will be
 |          converted into a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          The predicted values.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.RegressorMixin:
 |
 |  score(self, X, y, sample_weight=None)
 |      Return the coefficient of determination R^2 of the prediction.
 |
 |      The coefficient R^2 is defined as (1 - u/v), where u is the residual
 |      sum of squares ((y_true - y_pred) ** 2).sum() and v is the total
 |      sum of squares ((y_true - y_true.mean()) ** 2).sum().
 |      The best possible score is 1.0 and it can be negative (because the
 |      model can be arbitrarily worse). A constant model that always
 |      predicts the expected value of y, disregarding the input features,
 |      would get a R^2 score of 0.0.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Test samples. For some estimators this may be a
 |          precomputed kernel matrix or a list of generic objects instead,
 |          shape = (n_samples, n_samples_fitted),
 |          where n_samples_fitted is the number of
 |          samples used in the fitting for the estimator.
 |
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          True values for X.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights.
 |
 |      Returns
 |      -------
 |      score : float
 |          R^2 of self.predict(X) wrt. y.
 |
 |      Notes
 |      -----
 |      The R2 score used when calling ``score`` on a regressor will use
 |      ``multioutput='uniform_average'`` from version 0.23 to keep consistent
 |      with :func:`~sklearn.metrics.r2_score`. This will influence the
 |      ``score`` method of all the multioutput regressors (except for
 |      :class:`~sklearn.multioutput.MultiOutputRegressor`). To specify the
 |      default value manually and avoid the warning, please either call
 |      :func:`~sklearn.metrics.r2_score` directly or make a custom scorer with
 |      :func:`~sklearn.metrics.make_scorer` (the built-in scorer ``'r2'`` uses
 |      ``multioutput='uniform_average'``).
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.RegressorMixin:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from BaseForest:
 |
 |  apply(self, X)
 |      Apply trees in the forest to X, return leaf indices.
 |
 |      Parameters
 |      ----------
 |      X : {array-like or sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, its dtype will be converted to
 |          ``dtype=np.float32``. If a sparse matrix is provided, it will be
 |          converted into a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      X_leaves : array_like, shape = [n_samples, n_estimators]
 |          For each datapoint x in X and for each tree in the forest,
 |          return the index of the leaf x ends up in.
 |
 |  decision_path(self, X)
 |      Return the decision path in the forest.
 |
 |      .. versionadded:: 0.18
 |
 |      Parameters
 |      ----------
 |      X : {array-like or sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, its dtype will be converted to
 |          ``dtype=np.float32``. If a sparse matrix is provided, it will be
 |          converted into a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      indicator : sparse csr array, shape = [n_samples, n_nodes]
 |          Return a node indicator matrix where non zero elements
 |          indicates that the samples goes through the nodes.
 |
 |      n_nodes_ptr : array of size (n_estimators + 1, )
 |          The columns from indicator[n_nodes_ptr[i]:n_nodes_ptr[i+1]]
 |          gives the indicator value for the i-th estimator.
 |
 |  fit(self, X, y, sample_weight=None)
 |      Build a forest of trees from the training set (X, y).
 |
 |      Parameters
 |      ----------
 |      X : array-like or sparse matrix of shape (n_samples, n_features)
 |          The training input samples. Internally, its dtype will be converted
 |          to ``dtype=np.float32``. If a sparse matrix is provided, it will be
 |          converted into a sparse ``csc_matrix``.
 |
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          The target values (class labels in classification, real numbers in
 |          regression).
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights. If None, then samples are equally weighted. Splits
 |          that would create child nodes with net zero or negative weight are
 |          ignored while searching for a split in each node. In the case of
 |          classification, splits are also ignored if they would result in any
 |          single class carrying a negative weight in either child node.
 |
 |      Returns
 |      -------
 |      self : object
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from BaseForest:
 |
 |  feature_importances_
 |      Return the feature importances (the higher, the more important the
 |         feature).
 |
 |      Returns
 |      -------
 |      feature_importances_ : array, shape = [n_features]
 |          The values of this array sum to 1, unless all trees are single node
 |          trees consisting of only the root node, in which case it will be an
 |          array of zeros.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.ensemble._base.BaseEnsemble:
 |
 |  __getitem__(self, index)
 |      Return the index'th estimator in the ensemble.
 |
 |  __iter__(self)
 |      Return iterator over estimators in the ensemble.
 |
 |  __len__(self)
 |      Return the number of estimators in the ensemble.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : mapping of string to any
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as pipelines). The latter have parameters of the form
 |      ``<component>__<parameter>`` so that it's possible to update each
 |      component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : object
 |          Estimator instance.

In [72]:
rfr = RFR()

In [74]:
rfr = rfr.fit(X_train, y_train)

In [75]:
y_pred = rfr.predict(X_test)

In [77]:
y_pred[0]

29.27

In [76]:
r2_score(y_pred,y_test)

0.804911223966533

![](data/grid.png)

![](data/folds.jpg)

In [78]:
from sklearn.model_selection import GridSearchCV

In [80]:
grid_param = { #Son parametros que cambiaran en el modelo y se escojeran los mejores parametros
    'n_estimators':[i for i in range(100,201,10)],
    'criterion':['mse','mae'],
    'max_depth':[10,15,20,25]
}

In [83]:
grid_param

{'n_estimators': [100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200],
 'criterion': ['mse', 'mae'],
 'max_depth': [10, 15, 20, 25]}

In [84]:
random_forest_regresion = RFR()
random_forest_grid = GridSearchCV(random_forest_regresion, grid_param)

In [85]:
random_trained = random_forest_grid.fit(X_train,y_train)

In [86]:
random_trained.best_estimator_

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=20, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=110, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [92]:
dic_params = random_trained.best_params_
dic_params

{'criterion': 'mse', 'max_depth': 20, 'n_estimators': 110}

In [93]:
random_f_r_best_params = RFR(**dic_params) #puro modelo

In [94]:
rfr = random_f_r_best_params.fit(X_train, y_train) #Entrenamiento
y_pred = rfr.predict(X_test)
r2_score(y_pred,y_test)

0.8173153106671173

In [95]:
from sklearn.model_selection import cross_val_score

In [105]:
scores = cross_val_score(rfr, X_test,y_pred, cv = 5) #validacion con modelo entrenado

In [106]:
scores

array([0.95044622, 0.93220331, 0.95926539, 0.89916795, 0.75024634])